language: node_js
node_js:
  - 12
cache: yarn
addons:
  ssh_known_hosts: buechele.cc
install:
  - cd server
  - yarn
script:
  - yarn build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete --quiet $TRAVIS_BUILD_DIR/server/.nexus/build buechele@buechele:feedshare
  on:
    branch: main
